### ISSUE TITLE
`pds4_create_xml_index`: Give user error when label file is generated with errors

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-pds4indextools#40]
Right now if a label file is generated with errors such as:

```
            <doi>[[["KeyError('doi') at line 26"]]]</doi>
[[["KeyError('keyword') at line 27"]]]            <description>[[["KeyError('description') at line 30"]]]</description>
        </Citation_Information>
[[[IndexError(list index out of range) at line 41]]]
```

the only way the user knows is if they look at the label file by hand. The program should check for errors and display a message when the program is run.

**Comment by rfrenchseti** [comment]
In the documentation under "For reference, provided below are the full contents of the optional label classes:" I think every line should end with a colon. Right now if you copy this list into your yaml config file, it won't parse.

**Comment by rfrenchseti** [comment]
If there are no references, the label contains:

```
    <Reference_List>
    </Reference_List>
```

It seems like in this case the section should be left out entirely.

**Comment by rfrenchseti** [comment]
I'm not sure why, but this part of the label template doesn't work:

```
        $FOR(Citation_Information['keyword'])
            <keyword>$VALUE$</keyword>
        $END_FOR
```

If a `Citation_Information` section is provided in the user's config file, even if every field is empty, the label generation stops (without error!) at the beginning of the citation information section. For example this config file:

```
label-contents:
  version_id: '2.5'
  title: "This is a long string, with commas, & symbols, : <> stuff, etc."
  Citation_Information:
    author_list: me
    editor_list:
    publication_year:
    doi:
    keyword:
    description:
    Funding_Acknowledgement:
      funding_source:
      funding_year:
      funding_award:
      funding_acknowledgement_text:
```

If I remove that loop from the label template, it works.

Is this a bug in `PdsTemplate`?

**Comment by rfrenchseti** [comment]
The documentation for the label config is a little confusing. For example, `author_list` probably isn't actually expecting a list. If you give it:

```
  Citation_Information:
    author_list:
      me
      you
```

then it just separates them with spaces:

```
            <author_list>me you</author_list>
```

On the other hand, `keyword` really is expecting a list, and if you just give it a single keyword like the name implies, you definitely don't get what you expect:

```
    keyword: fred
```

yields

```
            <keyword>f</keyword>
            <keyword>r</keyword>
            <keyword>e</keyword>
            <keyword>d</keyword>
```

**Comment by rfrenchseti** [comment]
Likewise, let's say you put this in your config file:

```
  Modification_Detail:
    modification_date: "2020-01-01"
    version_id: 15.5
    description: This is a description
```

You get this:

```
        <Modification_History>
            <Modification_Detail>
                <modification_date>[[[TypeError(string indices must be integers, not 'str') at line 45]]]</modification_date>
                <version_id>[[[TypeError(string indices must be integers, not 'str') at line 46]]]</version_id>
                <description>[[[TypeError(string indices must be integers, not 'str') at line 47]]]</description>
            </Modification_Detail>
            <Modification_Detail>
                <modification_date>[[[TypeError(string indices must be integers, not 'str') at line 45]]]</modification_date>
                <version_id>[[[TypeError(string indices must be integers, not 'str') at line 46]]]</version_id>
                <description>[[[TypeError(string indices must be integers, not 'str') at line 47]]]</description>
            </Modification_Detail>
            <Modification_Detail>
                <modification_date>[[[TypeError(string indices must be integers, not 'str') at line 45]]]</modification_date>
                <version_id>[[[TypeError(string indices must be integers, not 'str') at line 46]]]</version_id>
                <description>[[[TypeError(string indices must be integers, not 'str') at line 47]]]</description>
            </Modification_Detail>
        </Modification_History>
```
